ingress:
  enabled: true
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt-prod
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
  hosts:
    - ${URL}
  tls:
    - hosts:
        - ${URL}
      secretName: ${CI_ENVIRONMENT_SLUG}-tls-jhub
proxy:
  secretToken: "${JUPYTERHUB_PROXY_TOKEN}"
  service:
    type: ClusterIP
    annotations:
      app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
      app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
hub:
  db:
    annotations:
      app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
      app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    pvc:
      annotations:
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
  service:
    annotations:
      app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
      app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}

singleuser:
  extraAnnotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
  # Mandatory for Bare Metal installation
  cloudMetadata:
    enabled: true
  # Defines the default image
  image:
    name: ${CI_APPLICATION_REPOSITORY}-code-server
    tag: ${CI_COMMIT_SHA}
  cpu:
    limit: 4
    guarantee: 1
  memory:
    limit: 8G
    guarantee: 1G
  profileList:
    - description: code-server
      default: true
      display_name: VScode
      kubespawner_override:
        cmd:
          - code-server
        image: ${CI_APPLICATION_REPOSITORY}-code-server:${CI_COMMIT_SHA}
        extra_containers:
          - name: code-hub-nginx
            image: ${CI_APPLICATION_REPOSITORY}-nginx:${CI_COMMIT_SHA}
  storage:
    type: dynamic
    extraLabels: {}
    extraVolumes: []
    extraVolumeMounts: []
    static:
      pvcName:
      subPath: '{username}'
    capacity: 20Gi
    homeMountPath: /home/coder
    dynamic:
      storageClass:
      pvcNameTemplate: claim-{username}{servername}
      volumeNameTemplate: volume-{username}{servername}
      storageAccessModes: [ReadWriteOnce]